#!/usr/bin/env -S python3 -u
import sys
import json
import socket
import select

class Router:
    def __init__(self, asn, neighbors):
        self.asn = asn
        self.neighbors = {}
        self.routes = {}
        self.announcements = {}
        self.sockets = {}

        for neighbor_arg in neighbors: